# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux
  - windows
julia:
  # - 1.4
  - nightly
branches:
  only:
    - master
notifications:
  email: false
codecov: true
