# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux
julia:
  - nightly
branches:
  only:
    - master
notifications:
  email: false
after_success:
  - codecov: true
